apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: traefik/whoami:v1.10
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: sample-app
spec:
  selector:
    app: hello-app
  ports:
    - port: 80
      targetPort: 80
